openapi: 3.0.0
info:
  title: Pet Store Service
  description: This is a pet store service.
  version: 0.0.0
tags: []
paths:
  /pets:
    get:
      operationId: Pets_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      required:
        - name
        - age
        - kind
      properties:
        name:
          type: string
          minLength: 100
        age:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
        kind:
          type: string
          enum:
            - dog
            - cat
            - fish
servers:
  - url: https://example.com
    description: The service endpoint
    variables: {}
