spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boilerplate
    username: boilerplate_user
    password: boilerplate_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
