server:
  address: 0.0.0.0
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mariadb://db:3306/boilerplate
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  threads:
    virtual:
      enabled: true
