server:
  address: 0.0.0.0
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boilerplate
    username: boilerplate_user
    password: boilerplate_pass
    driver-class-name: org.postgresql.Driver
  threads:
    virtual:
      enabled: true
