name: Build OCI image
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository }}
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE }}

      - uses: docker/bake-action@v6
        id: bake
        with:
          source: .
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          provenance: true
          sbom: true
          push: true

      - name: attest provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.IMAGE }}
          # https://github.com/docker/bake-action/issues/99
          subject-digest: ${{ fromJSON(steps.bake.outputs.metadata).default['containerimage.digest'] }}
          push-to-registry: true

      - name: attest SBOM
        uses: actions/attest-sbom@v3
        id: attest
        with:
          subject-name: ${{ env.IMAGE }}
          # https://github.com/docker/bake-action/issues/99
          subject-digest: ${{ fromJSON(steps.bake.outputs.metadata).default['containerimage.digest'] }}
          sbom-path: 'sbom.spdx.json'
          push-to-registry: true

